# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_or_not', models.IntegerField(choices=[(0, 'NOT CURRENT'), (1, 'CURRENT')], default=1)),
                ('project_status', models.IntegerField(choices=[(1, 'Stuck'), (2, 'Working'), (3, 'Done')], default=1)),
                ('due_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=80)),
                ('task_status', models.IntegerField(choices=[(1, 'Stuck'), (2, 'Working'), (3, 'Done')], default=1)),
                ('task_priority', models.IntegerField(choices=[(1, 'LOW'), (2, 'MIDDLE'), (3, 'HIGH')], default=1)),
                ('assign', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.Project')),
            ],
            options={
                'ordering': ['project', 'task_name'],
            },
        ),
    ]
