# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_project_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
