# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-17 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0004_auto_20191217_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_or_not',
            field=models.CharField(choices=[('NOT CURRENT', 'NOT CURRENT'), ('CURRENT', 'CURRENT')], default='CURRENT', max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('Stuck', 'Stuck'), ('Working', 'Working'), ('Done', 'Done')], default='Working', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MIDDLE', 'MIDDLE'), ('HIGH', 'HIGH')], default='HIGH', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Stuck', 'Stuck'), ('Working', 'Working'), ('Done', 'Done')], default='Working', max_length=10),
        ),
    ]
